added code from lecture 3
RusskovMatvey/first-repository pull request #2
Opened 2018-12-02 11:36 UTC by RusskovMatvey

Добавил код с третьей лекции.

2018-12-02 17:12 UTC, andrsuh requested changes

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/ArrayStack.java
> +        elements = (E[]) (new Object[capacity]);
redundant brackets

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/ArrayStack.java
> +        ensureCapacity(size+1);
formatting change. binary operators should be surrounded with spaces

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/ArrayStack.java
> +            newElements[i] = elements[i];
Some util methods from Arrays class may be useful

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/ArrayStack.java
> +        return elements[size];
Why should we increment size and then decrement it?

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/ArrayStack.java
> +        return elements[size-1];
formatting

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/LinkedStack.java
> +        public Node(Node<E> next, E value) {
Why should we have public constructor?

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/StackTest.java
> +        while (stack.size() != 0) {
You should get used to use methods like isEmpty rather than test if the size == 0 wherever it possible

2018-12-02 17:12 UTC, andrsuh commented on src/main/java/matvey/russkov/lecture3/StackTest.java
> +            LinkedStack<String> stack = new LinkedStack<String>();
You can store the implementation to the base class reference

2018-12-04 13:33 UTC, RusskovMatvey commented on src/main/java/matvey/russkov/lecture3/ArrayStack.java
> +        return elements[size];
Так как мы объединяем общую часть в методе pop(), и для всех стеков нужно было уменьшать size, но, как мы выяснили, в ArrayStack необходимо занулить предыдущий элемент. Поэтому я сделал такой костыль, дабы не ломать общую идею организации метода pop().

2018-12-04 13:42 UTC, RusskovMatvey commented on src/main/java/matvey/russkov/lecture3/StackTest.java
> +            LinkedStack<String> stack = new LinkedStack<String>();
Так делать предпочтительнее?

2018-12-04 14:16 UTC, RusskovMatvey commented on src/main/java/matvey/russkov/lecture3/LinkedStack.java
> +        public Node(Node<E> next, E value) {
действительно смыла в этом мало, так как наследоваться от Node нет необходимости. Исправлю.

2018-12-04 14:54 UTC, RusskovMatvey commented
Я все исправил.

2018-12-04 15:04 UTC, RusskovMatvey commented
Теперь точно все исправил

2018-12-04 16:10 UTC, andrsuh approved these changes
Great! Let's Squash and merge It

2018-12-04 20:03 UTC, merged